services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: factorial-http-app:latest
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      # - SERVER_PARALLELISM=4 # uncomment to override default
    ports:
      - "8080:8080"
    #depends_on:
      # - kafka 

  zookeeper:
    image: zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: apache/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"

